config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    member do
      put 'like' 
    end
  end

  get 'posts/new', to: 'posts#new', as: 'create_post'
  get 'posts/:id/edit', to: 'posts#edit', as: 'amend_post'
  patch 'posts/:id', to: 'posts#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    validates :caption, presence: true
    validates :image_url, presence: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  
    def index
      @posts = Post.all
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to posts_path, notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @post.update(post_params)
        redirect_to posts_path, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  
    def like
      @post.likes += 1
      @post.save
      redirect_to posts_path
    end
  
    private
  
    def set_post
      @post = Post.find(params[:id])
    end
  
    def post_params
      params.require(:post).permit(:caption, :image_url)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>This is Ruby on Rails</h1>
<p>This is the homepage for this web.</p>
<p>From index html erb file</p>

<%= link_to 'New Post', new_post_path %>
<% @posts.each do |post| %>
  <h2><%= post.caption %></h2>
  <%= image_tag post.image.url if post.image.present? %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Like', like_post_path(post), method: :put %>
  <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<p>From new html erb file</p>

<%= form_with(model: @post, local: true) do |form| %>
  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post' %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.caption %></h1>
<%= image_tag @post.image.url if @post.image.present? %>

<p>Likes: <%= @post.likes %></p>

<%= link_to "Like", like_post_path(@post), method: :put %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>